package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"log"

	"github.com/tkdn/gqlgen-subscription/backend/graph/model"
	"github.com/tkdn/gqlgen-subscription/backend/userctx"
)

// CreateJob is the resolver for the createJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, name string) (*model.Job, error) {
	return r.JobStore.Create(ctx, userctx.UserID(ctx), name)
}

// UpdateJobStatus is the resolver for the updateJobStatus field.
func (r *mutationResolver) UpdateJobStatus(ctx context.Context, id string, status model.JobState) (*model.Job, error) {
	return r.JobStore.UpdateStatus(ctx, userctx.UserID(ctx), id, status)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.Job, error) {
	return r.JobStore.List(ctx, userctx.UserID(ctx))
}

// JobStatuses is the resolver for the jobStatuses field.
func (r *subscriptionResolver) JobStatuses(ctx context.Context) (<-chan []*model.Job, error) {
	userID := userctx.UserID(ctx)

	notify, unsubscribe, err := r.Hub.Subscribe(userID)
	if err != nil {
		return nil, err
	}

	ch := make(chan []*model.Job, 1)

	// 接続直後に初期スナップショットを配信する。
	initial, err := r.JobStore.List(ctx, userID)
	if err != nil {
		unsubscribe()
		return nil, err
	}
	ch <- initial

	go func() {
		defer close(ch)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-notify:
				if !ok {
					return
				}
				jobs, err := r.JobStore.List(ctx, userID)
				if err != nil {
					// 検証目的のためログのみ出力し、既存の購読は継続する。
					log.Printf("jobStatuses: list jobs for %q: %v", userID, err)
					continue
				}
				select {
				case ch <- jobs:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
