package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"

	"github.com/tkdn/gqlgen-subscription/backend/graph/model"
	"github.com/tkdn/gqlgen-subscription/backend/userctx"
)

// CreateJob is the resolver for the createJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, name string) (*model.Job, error) {
	userID := userctx.UserID(ctx)

	job, err := r.JobStore.Create(ctx, userID, name)
	if err != nil {
		return nil, err
	}
	if err := r.Dispatcher.Dispatch(ctx, userID, job); err != nil {
		return nil, fmt.Errorf("dispatch job: %w", err)
	}
	return job, nil
}

// UpdateJobStatus is the resolver for the updateJobStatus field.
func (r *mutationResolver) UpdateJobStatus(ctx context.Context, id string, status model.JobState) (*model.Job, error) {
	return r.JobStore.UpdateStatus(ctx, userctx.UserID(ctx), id, status)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.Job, error) {
	return r.JobStore.List(ctx, userctx.UserID(ctx))
}

// JobsInvalidated is the resolver for the jobsInvalidated field.
func (r *subscriptionResolver) JobsInvalidated(ctx context.Context) (<-chan bool, error) {
	notify, unsubscribe, err := r.Hub.Subscribe(userctx.UserID(ctx))
	if err != nil {
		return nil, err
	}

	ch := make(chan bool, 1)
	// 購読していなかった間の更新は通知されないので、クライアントの状態は
	// 購読の開始時点で古い可能性がある。そのため購読の開始自体を最初の
	// invalidationとして送る。Hubへの登録後に送るので、以降の更新は通知で届く。
	ch <- true

	go func() {
		defer close(ch)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-notify:
				if !ok {
					return
				}
				select {
				case ch <- true:
				default:
					// 未送信のinvalidationがchに残っていて空きがない。invalidationは
					// 中身を持たないので、残っている1件が届けばクライアントはその時点の
					// 最新を取り直し、この通知の元になった更新もそこに含まれる。
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
